import { Roboto, Playfair } from "next/font/google";
import './globals.css'
import 'react-tooltip/dist/react-tooltip.css'

const roboto = Roboto({
  subsets: ["latin"],
  display: 'swap',
  preload: true,
  variable: '--font-roboto'
})

const playfair = Playfair({
  subsets: ["latin"],
  display: 'swap',
  preload: true,
  variable: '--font-playfair'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${playfair.variable} antialiased`} >
        {children}
      </body>
    </html>
  );
}
